### ISSUE TITLE
reference.index  points to the wrong condition

### ISSUE THREAD

**Issue by fnaji** [tercen/DESeq2_two_conditions_operator#6]
The reference.index should contain the index that points to the right factor in a list ordered alphanumerically (i.e. like the color legend is ordered)

instead, the reference.index is using the data colored in the cross-tab and the first color to appear in the data is what the reference.index is using

**Comment by agouy** [comment]
Fixed in https://github.com/tercen/DESeq2_operator/releases/tag/0.1.4
